# ansible-playbook pub_key.yml --ask-pass
- name: Copy Key
  hosts: all
  tasks:
    - name: Install Key
      authorized_key:
        user: mklouda
        state: present
        key: "{{ lookup('file', '/home/mklouda/.ssh/ansible.pub') }}"
