--- 
- 
  become: true
  gather_facts: true
  hosts: all
  strategy: free
  tasks: 
    - 
      ansible.builtin.dnf: 
        update_cache: true
      name: "update dnf cache"
      when: "ansible_pkg_mgr == \"dnf\""
    - 
      name: "Enable EPEL Repository on Rocky 8"
      package: 
        name: epel-release
        state: present
