--- 
- 
  become: true
  gather_facts: true
  hosts: all
  tasks: 
    - 
      ansible.builtin.apt: 
        update_cache: true
      name: "update apt cache"
      when: "ansible_pkg_mgr == \"apt\""
    - 
      apt: 
        name: 
          - ncdu
          - whois
          - mc
          - htop
          - iotop
          - tcpdump
          - net-tools
          - sysstat
          - wget
          - tmux
          - screen
          - zsh
          - zsh-syntax-highlighting
          - git
          - curl
          - gpg
          - traceroute
          - open-vm-tools
          - httping
          - freeipa-client
          - vim
        state: latest
      name: "Install baseline packages for Debian with apt"
      when: "ansible_distribution == \"Debian\""
    - 
      ansible.builtin.dnf: 
        update_cache: true
      name: "update dnf cache"
      when: "ansible_pkg_mgr == \"dnf\""
    - 
      dnf: 
        name: 
          - ncdu
          - whois
          - mc
          - htop
          - iotop
          - tcpdump
          - net-tools
          - sysstat
          - wget
          - tmux
          - screen
          - zsh-syntax-highlighting
          - git
          - curl
          - gpg
          - traceroute
          - open-vm-tools
          - httping
          - iproute-tc
          - bind-utils
          - freeipa-client
          - vim
          - iproute-tc
          - yum-plugin-versionlock
        state: latest
      name: "Install baseline packages for Rocky with dnf"
      when: "ansible_pkg_mgr == \"dnf\""
