--- 
- 
  become: true
  gather_facts: true
  hosts: all
  tasks: 
    - 
      apt: 
        update_cache: true
      name: "update repository index"
      when: "ansible_facts['os_family'] == 'Debian' and ansible_facts ['distribution_major_version'] >= '10'"
    - 
      apt: 
        name: 
          - ncdu
          - whois
          - mc
          - htop
          - iotop
          - tcpdump
          - net-tools
          - sysstat
          - wget
          - tmux
          - screen
          - git
          - curl
          - gpg
          - traceroute
          - open-vm-tools
          - httping
          - freeipa-client
          - vim
        state: present
      name: "install baseline packages for Debian"
      when: "ansible_facts['os_family'] == 'Debian' and ansible_facts ['distribution_major_version'] >= '10'"
    - 
      name: "install baseline packages for Rocky"
      package: 
        name: 
          - ncdu
          - whois
          - mc
          - htop
          - iotop
          - tcpdump
          - net-tools
          - sysstat
          - wget
          - tmux
          - screen
          - git
          - curl
          - gpg
          - traceroute
          - open-vm-tools
          - httping
          - yum-plugin-versionlock
          - bind-utils
          - freeipa-client
          - vim
          - zsh-syntax-highlighting
        state: present
