--- 
- 
  become: true
  gather_facts: true
  hosts: test-rocky.home.klouda.co
  strategy: free
  tasks: 
    - 
      package: 
        update_cache: true
      name: "update repository index"
    - 
      package: 
        name: epel-release
        state: present
      name: "Enable EPEL Repository on Rocky 8"
