--- 
- 
  become: true
  gather_facts: true
  hosts: all
  strategy: free
  tasks: 
    - 
      dnf: 
        update_cache: true
      name: "update repository index"
    - 
      dnf: 
        name: epel-release
        state: latest
      name: "Enable EPEL Repository on Rocky 8"
      when: "ansible_facts['os_family'] == 'Rocky' and ansible_facts ['distribution_major_version'] >= '8'"
  tasks: 
    - 
      apt: 
        update_cache: true
      name: "update repository index"
    - 
      apt: 
        name: epel-release
        state: latest
      name: "Enable EPEL Repository on Debian 10"
      when: "ansible_facts['os_family'] == 'Debian' and ansible_facts ['distribution_major_version'] >= '10'"
