---
- hosts: all
  gather_facts: True
  become: true
  strategy: free
  tasks:
  - name: Enable EPEL Repository on Rocky 8
    dnf:
      name: epel-release
      state: latest
    when: ansible_facts['os_family'] == 'Rocky' and ansible_facts ['distribution_major_version'] >= '8'

  - name: Enable EPEL Repository on Rocky 9
    yum:
      name: epel-release
      state: latest
    when: ansible_facts['os_family'] == 'Rocky' and ansible_facts ['distribution_major_version'] == '9'
