--- 
- 
  become: true
  hosts: all
  gather_facts: true
  tasks: 
    - 
      apt: 
        update_cache: true
      name: "update repository index"
      when: "ansible_facts['os_family'] == 'Debian' and ansible_facts ['distribution_major_version'] >= '10'"
    - 
      apt: 
        name: 
          - ncdu
          - whois
          - mc
          - htop
          - iotop
          - tcpdump
          - net-tools
          - sysstat
          - wget
          - tmux
          - screen
          - git
          - curl
          - gpg
          - traceroute
          - open-vm-tools
          - httping
          - freeipa-client
          - vim
        state: latest
      name: "install baseline packages for Debian"
      when: "ansible_facts['os_family'] == 'Debian' and ansible_facts ['distribution_major_version'] >= '10'"
    - 
      dnf: 
        update_cache: true
      name: "update repository index"
      when: "ansible_facts['os_family'] == 'Rocky' and ansible_facts ['distribution_major_version'] >= '8'"
    - 
      dnf: 
        name: 
          - ncdu
          - whois
          - mc
          - htop
          - iotop
          - tcpdump
          - net-tools
          - sysstat
          - wget
          - tmux
          - screen
          - git
          - curl
          - gpg
          - traceroute
          - open-vm-tools
          - httping
          - iproute-tc
          - yum-plugin-versionlock
          - bind-utils
          - freeipa-client
          - vim
        state: latest
      name: "install baseline packages for Rocky"
      when: "ansible_facts['os_family'] == 'Rocky' and ansible_facts ['distribution_major_version'] >= '8'"
