--- 
- 
  gather_facts: true
  hosts: all
  tasks: 
    - 
      apt: 
        name: zsh
        state: latest
      become: true
      name: "Install ZSH"
      when: "ansible_facts['os_family'] == 'Debian' and ansible_facts  ['distribution_major_version'] >= '10'"
    - 
      become: true
      dnf: 
        name: zsh
        state: latest
      name: "Install ZSH"
      when: "ansible_facts['os_family'] == 'Rocky' and ansible_facts  ['distribution_major_version'] >= '8'"
